### ISSUE TITLE
V2 Roadmap

### ISSUE THREAD

**Issue by atymic** [thomasjohnkane/snooze#63]
- [x] Fix #52 issues with psql 
- [ ] Fix #60 by publishing migrations
- [ ] Fix #47 by adding a `tries` column to migration
- [ ] Clean up code issues
- [ ] Drop old laravel version support

**Comment by AEK-BKF** [comment]
Hi @atymic , 
Any updates here ? Thanks :)
